server:
  port: 8080

spring:
  application:
    name: boot_example
  #redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 106.75.216.194
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.75.216.194:3306/mybatis-all?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: QWERwasd*963.
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000


  rabbitmq:
    host: 106.75.216.194
    port: 5672
    username: guest
    password: guest
    connection-timeout: 150000


#mybatis
mybatis:
  mapper-locations: classpath:com/magic/mapper/*.xml
  type-aliases-package: com/magic/dto
pagehelper:
  helper-dialect: mysql
logging:
  config: classpath:logback-spring.xml
